development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: skate_dev
  pool: 5
  username: <%= ENV['SKATE_DB_USER'] || 'user' %>
  password: <%= ENV['SKATE_DB_PASS'] || 'pass' %>
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: skate_test
  pool: 5
  username: <%= ENV['SKATE_DB_USER'] || 'user' %>
  password: <%= ENV['SKATE_DB_PASS'] || 'pass' %>
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: skate_prod
  pool: 5
  username: <%= ENV['SKATE_DB_USER'] || 'user' %>
  password: <%= ENV['SKATE_DB_PASS'] || 'pass' %>
  host: localhost
